name: ekyc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_utils_project: ^1.2.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  camera_camera: ^3.0.0
  m7_livelyness_detection: ^0.0.6+4
  http: ^1.2.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

