///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String clip = 'assets/images/clip.png';
  static const String livelynessDetection =
      'assets/images/livelyness_detection.svg';
  static const String onBoarding1 = 'assets/images/onBoarding1.svg';
  static const String onBoarding2 = 'assets/images/onBoarding2.svg';
  static const String onBoarding3 = 'assets/images/onBoarding3.svg';
  static const String onBoarding4 = 'assets/images/onBoarding4.svg';
  static const String oops = 'assets/images/oops.png';
  static const String selfie = 'assets/images/selfie.png';
  static const String splash = 'assets/images/splash.svg';
  static const String splash2 = 'assets/images/splash2.svg';
  static const String success = 'assets/images/success.png';
}
